seed: 2024
device: cuda:0
data:
  n_fold: 5
  # name: "IMDB_dir_form", "IMDB_dir_genre", "IMDB_wri_form", "IMDB_wri_genre", "twitter_friend", "steam_player"
  # name: "RHG_3", "RHG_10", "RHG_table", "RHG_pyramid"
  name: IMDB_dir_form #steam_player
  root: ${hydra:runtime.cwd}/data
  degree_as_tag: true
  batch_size: 32
  num_workers: 0

optim:
  lr: 0.01
  weight_decay: 5e-4
  max_epoch: 50
  batch_size: 32

model:
  # name: gcn, graphsage, gin, graphsnn, hgnn, hgnnp, hgin, ia_hgin, allsettransformer, unigcn2, unigat, ed_hnn, hypergcn
  name: ia_hgin
  hidden_dim: 64

hydra:
  run:
    dir: cache/${data.name}__${model.name}/${now:%Y-%m-%d}_${now:%H-%M-%S}
